server:
  port: 8001
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.203.134:3306/xprojectdb?useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: xprojectuser
    password: xproject123

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml